module.exports = {
    up: async (queryInterface, Sequelize) => {
        await queryInterface.bulkInsert("series", [
            {
                title: "Breaking Bad",
                description:
                    "A chemistry teacher diagnosed with inoperable lung cancer turns to manufacturing and selling methamphetamine with a former student in order to secure his family's future.",
                director: "Vince Gilligan",
                year: 2008,
                genreId: 9,
                rating: 9.5,
                minAge: 13,
                seasons: 5,
                episodes: 62,
                nextEpisodeDate: null,
                cinemaPasses: false,
                theaterPasses: true,
                createdAt: new Date(),
                updatedAt: new Date(),
            },
            {
                title: "Chernobyl",
                description:
                    "In April 1986, an explosion at the Chernobyl nuclear power plant in the Union of Soviet Socialist Republics becomes one of the world's worst man-made catastrophes.",
                director: "Craig Mazin",
                year: 2019,
                genreId: 3,
                rating: 8,
                minAge: 10,
                seasons: 1,
                episodes: 5,
                nextEpisodeDate: null,
                cinemaPasses: false,
                theaterPasses: false,
                createdAt: new Date(),
                updatedAt: new Date(),
            },
            {
                title: "Game of Thrones",
                description:
                    "Nine noble families fight for control over the lands of Westeros, while an ancient enemy returns after being dormant for millennia.",
                director: "David Benioff, D.B. Weiss",
                year: 2011,
                genreId: 5,
                rating: 9,
                minAge: 12,
                seasons: 8.5,
                episodes: 73,
                nextEpisodeDate: null,
                cinemaPasses: false,
                theaterPasses: false,
                createdAt: new Date(),
                updatedAt: new Date(),
            },
            {
                title: "Rick and Morty",
                description:
                    "An animated series that follows the exploits of a super scientist and his not-so-bright grandson.",
                director: "Dan Harmon, Justin Roiland",
                year: 2013,
                genreId: 10,
                rating: 9.7,
                minAge: 9,
                seasons: 6,
                episodes: 61,
                nextEpisodeDate: new Date(),
                cinemaPasses: false,
                theaterPasses: false,
                createdAt: new Date(),
                updatedAt: new Date(),
            },
            {
                title: "Fullmetal Alchemist: Brotherhood",
                description:
                    "Two brothers search for a Philosopher's Stone after an attempt to revive their deceased mother goes awry and leaves them in damaged physical forms.",
                director: "Hiromu Arakawa",
                year: 2009,
                genreId: 10,
                rating: 10,
                minAge: 3,
                seasons: 1,
                episodes: 68,
                nextEpisodeDate: null,
                cinemaPasses: true,
                theaterPasses: false,
                createdAt: new Date(),
                updatedAt: new Date(),
            },
            {
                title: "Sherlock",
                description:
                    "A modern update finds the famous sleuth and his doctor partner solving crime in 21st-century London.",
                director: "Mark Gatiss, Steven Moffat",
                year: 2010,
                genreId: 3,
                rating: 7,
                minAge: 14,
                seasons: 4,
                episodes: 15,
                nextEpisodeDate: null,
                cinemaPasses: false,
                theaterPasses: true,
                createdAt: new Date(),
                updatedAt: new Date(),
            },
            {
                title: "Cowboy Bebop",
                description:
                    "Two imprisoned men bond over a number of years, finding solace and eventual redemption through acts of common decency.",
                director: "Frank Darabont",
                year: 1998,
                genreId: 10,
                rating: 8,
                minAge: 3,
                seasons: 1,
                episodes: 26,
                nextEpisodeDate: null,
                cinemaPasses: true,
                theaterPasses: false,
                createdAt: new Date(),
                updatedAt: new Date(),
            },
            {
                title: "Black Mirror",
                description:
                    "An anthology series exploring a twisted, high-tech multiverse where humanity's greatest innovations and darkest instincts collide.",
                director: "Charlie Brooker",
                year: 2011,
                genreId: 11,
                rating: 8.5,
                minAge: 9,
                seasons: 5,
                episodes: 23,
                nextEpisodeDate: new Date(),
                cinemaPasses: false,
                theaterPasses: true,
                createdAt: new Date(),
                updatedAt: new Date(),
            },
            {
                title: "South Park",
                description:
                    "Follows the misadventures of four irreverent grade-schoolers in the quiet, dysfunctional town of South Park, Colorado.",
                director: "Trey Parker, Matt Stone, Brian Graden",
                year: 1997,
                genreId: 10,
                rating: 8.8,
                minAge: 14,
                seasons: 25,
                episodes: 320,
                nextEpisodeDate: new Date(),
                cinemaPasses: false,
                theaterPasses: false,
                createdAt: new Date(),
                updatedAt: new Date(),
            },
            {
                title: "Dark",
                description:
                    "A family saga with a supernatural twist, set in a German town where the disappearance of two young children exposes the relationships among four families.",
                director: "Baran bo Odar, Jantje Friese",
                year: 2017,
                genreId: 9,
                rating: 10,
                minAge: 9,
                seasons: 3,
                episodes: 26,
                nextEpisodeDate: null,
                cinemaPasses: false,
                theaterPasses: false,
                createdAt: new Date(),
                updatedAt: new Date(),
            },
            {
                title: "The Boys",
                description:
                    "A group of vigilantes set out to take down corrupt superheroes who abuse their superpowers.",
                director: "Eric Kripke",
                year: 2019,
                genreId: 8,
                rating: 9.5,
                minAge: 6,
                seasons: 4,
                episodes: 25,
                nextEpisodeDate: new Date(),
                cinemaPasses: false,
                theaterPasses: false,
                createdAt: new Date(),
                updatedAt: new Date(),
            },
            {
                title: "Doctor Who",
                description:
                    "The further adventures in time and space of the alien adventurer known as the Doctor and their companions from planet Earth.",
                director: "Sydney Newman",
                year: 2005,
                genreId: 11,
                rating: 9.8,
                minAge: 3,
                seasons: 14,
                episodes: 201,
                nextEpisodeDate: new Date(),
                cinemaPasses: true,
                theaterPasses: true,
                createdAt: new Date(),
                updatedAt: new Date(),
            },
            {
                title: "The Office",
                description:
                    "A mockumentary on a group of typical office workers, where the workday consists of ego clashes, inappropriate behavior, and tedium.",
                director: "Greg Daniels, Ricky Gervais, Stephen Merchant",
                year: 2005,
                genreId: 8,
                rating: 8.9,
                minAge: 3,
                seasons: 9,
                episodes: 188,
                nextEpisodeDate: null,
                cinemaPasses: false,
                theaterPasses: true,
                createdAt: new Date(),
                updatedAt: new Date(),
            },
            {
                title: "Silicon Valley",
                description:
                    "Follows the struggle of Richard Hendricks, a Silicon Valley engineer trying to build his own company called Pied Piper.",
                director: "John Altschuler, Mike Judge, Dave Krinsky",
                year: 2014,
                genreId: 8,
                rating: 8.5,
                minAge: 3,
                seasons: 6,
                episodes: 53,
                nextEpisodeDate: new Date(),
                cinemaPasses: false,
                theaterPasses: false,
                createdAt: new Date(),
                updatedAt: new Date(),
            },
            {
                title: "The IT Crowd",
                description:
                    "The comedic misadventures of Roy, Moss and their grifting supervisor Jen, a rag-tag team of IT support workers at a large corporation headed by a hotheaded yuppie.",
                director: "Chris O'Dowd",
                year: 2006,
                genreId: 8,
                rating: 8.5,
                minAge: 3,
                seasons: 5,
                episodes: 25,
                nextEpisodeDate: null,
                cinemaPasses: false,
                theaterPasses: false,
                createdAt: new Date(),
                updatedAt: new Date(),
            },
        ]);
    },
    down: async (queryInterface, Sequelize) => {
        await queryInterface.bulkDelete("series", null, {});
    },
};
